"""Campaign A (transfer program): three independent geometry-stratified HiLiftAeroML
training draws at 35 and 210 cases, their dataset YAML variants, and the 72-lane table.

Reads ONLY `full_train` and `full_val` of the dataset-root manifest (every `*_test`
key is sealed and never read). Case names are `geo_LHC###_AoA_##`; a geometry is
the LHC id, an operating point the angle of attack (10 angles, 4..22 deg).

Stratification rule (stated in PREREG.md):
  n = 35  : 35 distinct geometries (no geometry repeated), angles balanced
            (four cases at five angles, three at the other five, angle sets
            chosen at random per draw); this mirrors the curated split's
            character (33 geometries, 3-7 cases per angle) without copying it.
  n = 210 : full_train holds 180 geometries x 7 angles (1,260 cases; the
            validation set full_val holds 180 cases at other angles of 118 of
            those geometries and so shares geometries with training, as the
            curated splits do).
            Every one of the 180 geometries contributes one case and 30
            randomly chosen geometries a second one at a different angle
            (<= 2 cases per geometry), angles balanced at 21 per angle.
Validation is `full_val` (the shared 180 cases) for every draw.

Usage (cluster, recipe venv python):
  python build_campaign_a.py            # writes manifests, yaml variants, lane table
"""
import json, random, re, sys
from collections import defaultdict
from pathlib import Path

DATASET_ROOT = Path("/scratch/fsw/portfolios/coreai/projects/coreai_modulus_cae/datasets/PhysicsNeMo-HighLiftAeroML")
T = Path("/scratch/fsw/portfolios/coreai/projects/coreai_modulus_cae/users/psharpe/agents/2026-08-09-mt2-stage0")
MAN_DIR = T / "transfer" / "manifests"
BASE_YAML = T / "recipe_support" / "datasets" / "highlift_surface.yaml"
LANES = T / "transfer" / "campaign_a_lanes.tsv"
DRAWS = {1: 101, 2: 102, 3: 103}
SIZES = (35, 210)
ANGLES = list(range(4, 23, 2))


def case_present(case: str) -> bool:
    case_dir = DATASET_ROOT / case
    if not case_dir.is_dir():
        return False
    for pdmsh in case_dir.glob("domain_*.pdmsh"):
        td = pdmsh / "_tensordict"
        v, g = td / "boundaries" / "vehicle", td / "global_data"
        if v.is_dir() and any(v.iterdir()) and g.is_dir() and any(g.iterdir()):
            return True
    return False


def parse(case):
    m = re.match(r"geo_(LHC\d+)_AoA_(\d+)$", case)
    return m.group(1), int(m.group(2))


def draw_35(pool, rng):
    """35 distinct geometries, angles balanced: 5 angles x 4 + 5 angles x 3."""
    by_angle = defaultdict(list)
    for c in pool:
        by_angle[parse(c)[1]].append(c)
    angles = ANGLES[:]; rng.shuffle(angles)
    quota = {a: (4 if i < 5 else 3) for i, a in enumerate(angles)}
    used_geos, chosen = set(), []
    for a in angles:
        cands = [c for c in by_angle[a] if parse(c)[0] not in used_geos]
        rng.shuffle(cands)
        for c in cands[: quota[a]]:
            chosen.append(c); used_geos.add(parse(c)[0])
    assert len(chosen) == 35 and len(used_geos) == 35, (len(chosen), len(used_geos))
    return sorted(chosen)


def draw_210(pool, rng):
    """180 geometries x 1 case + 30 geometries x a second case; 21 cases per angle."""
    geos = sorted({parse(c)[0] for c in pool}); assert len(geos) == 180, len(geos)
    by_geo = defaultdict(dict)
    for c in pool:
        g, a = parse(c); by_geo[g][a] = c
    for attempt in range(200):
        angle_count = {a: 0 for a in ANGLES}; chosen = []; ok = True
        order = geos[:]; rng.shuffle(order)
        second = set(rng.sample(geos, 30))
        for g in order:
            need = 2 if g in second else 1
            avail = [a for a in ANGLES if a in by_geo[g] and angle_count[a] < 21]
            rng.shuffle(avail)
            avail.sort(key=lambda a: angle_count[a])  # fill the least-used angles first, ties random
            if len(avail) < need:
                ok = False; break
            for a in avail[:need]:
                chosen.append(by_geo[g][a]); angle_count[a] += 1
        if ok and len(chosen) == 210 and all(v == 21 for v in angle_count.values()):
            return sorted(chosen)
    raise RuntimeError("could not balance the 210-case draw")


def write_variant_yaml(tag: str, manifest_path: Path) -> Path:
    text = BASE_YAML.read_text()
    out_text, n = re.subn(r"(?m)^manifest: .*$", f"manifest: {manifest_path}", text)
    assert n == 1, n
    header = (f"# GENERATED by transfer_program/studies/campaign_a_draws/build_campaign_a.py -- do not edit.\n"
              f"# Campaign A draw {tag!r}: identical pipeline to highlift_surface.yaml; only the manifest differs.\n")
    out = BASE_YAML.parent / f"highlift_surface_{tag}.yaml"
    out.write_text(header + out_text)
    return out


def main():
    MAN_DIR.mkdir(parents=True, exist_ok=True)
    src = json.loads((DATASET_ROOT / "manifest.json").read_text())
    train_pool = [c for c in src["full_train"] if case_present(c)]
    val = sorted(c for c in src["full_val"] if case_present(c))
    print(f"full_train present {len(train_pool)}/{len(src['full_train'])}; full_val present {len(val)}/{len(src['full_val'])}")
    summary = {"val_n": len(val), "draws": {}}
    for d, seed in DRAWS.items():
        for n in SIZES:
            rng = random.Random(seed * 1000 + n)
            chosen = draw_35(train_pool, rng) if n == 35 else draw_210(train_pool, rng)
            tag = f"draw{d}_n{n}"
            man = MAN_DIR / f"hl_{tag}_manifest.json"
            man.write_text(json.dumps({"train": chosen, "val": val}, indent=1))
            write_variant_yaml(tag, man)
            geos = {parse(c)[0] for c in chosen}; ang = defaultdict(int)
            for c in chosen: ang[parse(c)[1]] += 1
            summary["draws"][tag] = {"n": len(chosen), "geometries": len(geos), "per_angle": dict(sorted(ang.items())), "seed": seed}
            print(tag, len(chosen), "cases", len(geos), "geometries", dict(sorted(ang.items())))
    # overlap between draws (informative)
    for n in SIZES:
        sets = [set(json.loads((MAN_DIR / f"hl_draw{d}_n{n}_manifest.json").read_text())["train"]) for d in DRAWS]
        summary[f"pairwise_overlap_n{n}"] = [len(sets[i] & sets[j]) for i in range(3) for j in range(i + 1, 3)]
    (MAN_DIR / "campaign_a_summary.json").write_text(json.dumps(summary, indent=1))
    # lane table: idx arm model extra dataset lr seed tokens run_id
    ARMS = [("gt", "geotransolver_surface", "forward_kwargs.global_embedding=global_data.U_inf_dir", "1.0e-3"),
            ("transolver", "transolver_surface", "forward_kwargs.fx.source=global_data.U_inf_dir", "3.0e-3"),
            ("isla", "mt2_surface", "model.out_scalars=3 model.out_vectors=2", "1.0e-3"),
            ("islanw", "mt2_surface", "model.out_scalars=3 model.out_vectors=2 +model.use_measure_weights=false", "1.0e-3")]
    rows = ["idx\tarm\tmodel\textra\tdataset\tlr\tseed\ttokens\trun_id"]; idx = 0
    for n in SIZES:
        for d in DRAWS:
            for arm, model, extra, lr in ARMS:
                for seed in (42, 43, 44):
                    rows.append(f"{idx}\tA\t{model}\t{extra}\thighlift_surface_draw{d}_n{n}\t{lr}\t{seed}\t10000\tcampA_hl_{arm}_n{n}_d{d}_seed{seed}")
                    idx += 1
    LANES.write_text("\n".join(rows) + "\n")
    print(f"wrote {LANES} with {idx} lanes")


if __name__ == "__main__":
    main()
